# Generated by Django 3.1 on 2020-08-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='currenct',
            new_name='currency',
        ),
    ]
