# Generated by Django 3.1 on 2020-08-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0003_auto_20200813_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(default='USD - United States Dollar', max_length=255),
        ),
    ]
